name: Static Code Check

on: [push]

jobs:
  check-code:

    name: "Static Code Check"
    runs-on: "ubuntu-24.04"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pre-commit
        run: python -m pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
